---
init_tasks:
  - name: Add test domain
    type: mysql-client
    script: init_tasks/add_domain.sh
    args: {{ default_domain }}
  
  - name: Reload domains
    type: opensips-cli
    args: -d -x mi domain_reload
    require:
      after:
        task: Add test domain

  - name: Create caller
    type: opensips-cli
    args: -d -x user add {{ caller }}@{{ default_domain }} {{ caller_password }}
    require:
      after:
        task: Reload domains

  - name: Create callee
    type: opensips-cli
    args: -d -x user add {{ callee }}@{{ default_domain }} {{ callee_password }}
    require:
      after:
        task: Reload domains

  - name: Enable caller
    type: mysql-client
    script: init_tasks/enable_user.sh
    args: {{ caller }} {{ default_domain }}
    require:
      after:
        task: Create caller
        wait: 1
    
  - name: Enable callee
    type: mysql-client
    script: init_tasks/enable_user.sh
    args: {{ callee }} {{ default_domain }}
    require:
      after:
        task: Create callee
        wait: 1


cleanup_tasks:
  - name: Delete caller
    type: opensips-cli
    args: -d -x user delete {{ caller }}@{{ default_domain }}

  - name: Delete callee
    type: opensips-cli
    args: -d -x user delete {{ callee }}@{{ default_domain }}

  - name: Delete test domain
    type: mysql-client
    script: cleanup_tasks/remove_domain.sh
    args: {{ default_domain }}
    require:
      after:
        task: Delete caller
      after:
        task: Delete callee
  
  - name: Reload domains
    type: opensips-cli
    args: -d -x mi domain_reload
    require:
      after:
        task: Delete test domain


defaults:
  opensips-cli:
    mi_ip: {{ opensips_ip }}
    options:
      database_user_url: mysql://{{ mysql_user }}:{{ mysql_password }}@{{ opensips_ip }}/{{ database }}
  uac-sipp:
    proxy: {{ opensips_ip }}:{{ opensips_port }}
    keys:
      domain: {{ default_domain }}
      caller: {{ caller }}
      callee: {{ callee }}
  mysql-client:
    host: {{ opensips_ip }}
    user: {{ mysql_user }}
    password: {{ mysql_password }}
    database: {{ database }}
