---
init_tasks:
  - name: Create caller
    type: opensips-cli
    args: -d -x user add {{ caller }}@{{ default_domain }} {{ caller_password }}
    options:
      database_user_url: mysql://opensips:opensipsrw@{{ opensips_ip }}/opensips

  - name: Create callee
    type: opensips-cli
    args: -d -x user add {{ callee }}@{{ default_domain }} {{ callee_password }}
    options:
      database_user_url: mysql://opensips:opensipsrw@{{ opensips_ip }}/opensips


cleanup_tasks:
  - name: Delete caller
    type: opensips-cli
    args: -d -x user delete {{ caller }}@{{ default_domain }}
    options:
      database_user_url: mysql://opensips:opensipsrw@{{ opensips_ip }}/opensips


  - name: Delete callee
    type: opensips-cli
    args: -d -x user delete {{ callee }}@{{ default_domain }}
    options:
      database_user_url: mysql://opensips:opensipsrw@{{ opensips_ip }}/opensips


defaults:
  opensips-cli:
    mi_ip: {{ opensips_ip }}
  uac-sipp:
    proxy: {{ opensips_ip }}:{{ opensips_port }}
    keys:
      domain: {{ default_domain }}
      caller: {{ caller }}
      callee: {{ callee }}
  mysql-client:
    host: {{ opensips_ip }}
    user: {{ mysql_user }}
    password: {{ mysql_password }}
    database: {{ database }}
