---
name: Run SIPSsert tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 2 * * Mon'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Fix HOST_IP env
      run: |
        HOST_IP=$(hostname -I | cut -d ' ' -f 1)
        sed "s/^HOST_IP=.*/HOST_IP=$HOST_IP/g" -i .env
      shell: bash

    - name: Setup Docker Compose
      uses: hoverkraft-tech/compose-action@v2.0.2

    - name: Run SIPSSert tests
      run: |
        ./run-sipssert.sh

